from setuptools import setup, find_packages

setup(
    name="xgboostlss",
    version="0.4.1",
    description="XGBoostLSS - An extension of XGBoost to probabilistic modelling",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="Alexander Maerz",
    author_email="alex.maerz@gmx.net",
    url="https://github.com/StatMixedML/XGBoostLSS",
    license="Apache License 2.0",
    packages=find_packages(exclude=["docs", "tests*"]),
    include_package_data=True,
    package_data={"": ["datasets/*.csv"]},
    zip_safe=True,
    python_requires=">=3.8",
    install_requires=[
        "xgboost>=1.2.0",
        "torch>=2.0.1",
        "pyro-ppl>=1.5.0",
        "optuna>=3.0.0",
        "properscoring>=0.1",
        "scikit-learn>=1.0.2",
        "numpy>=1.22.1",
        "pandas>=2.0.3",
        "plotnine>=0.8.0",
        "scipy>=1.0.0",
        "seaborn>=0.1.0",
        "torchlambertw @ git+ssh://git@github.com/gmgeorg/torchlambertw.git#egg=torchlambertw-0.0.2",
        "tqdm>=4.0.0",
        "matplotlib>=3.6.0",
    ],
    extras_require={"docs": ["mkdocs", "mkdocstrings[python]", "mkdocs-jupyter"]},
    test_suite="tests",
    tests_require=["flake8", "pytest"],
)
